# Host composer input; installation does not activate this configuration.
hostonly="no"
hostonly_cmdline="no"
uefi="no"
filesystems+=" ext4 "
omit_dracutmodules+=" network plymouth crypt systemd-cryptsetup syslog lvm mdraid btrfs "
